- name: copy
  copy: src=nginx-1.16.1-1.el7.ngx.x86_64.rpm dest=/tmp/nginx-1.16.1-1.el7.ngx.x86_64.rpm

- name: install
  yum: name=/tmp/nginx-1.16.1-1.el7.ngx.x86_64.rpm state=latest

- name: conf
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ project }}.conf backup=yes
  notify: reload
  tags: nginx_conf

- name: start service
  service: name=nginx state=started enable=yes